name = "OpenModelicaParser"
uuid = "3cc3926e-259e-5855-988e-4819684349c8"
authors = ["Adrian Pop <adrian.pop@liu.se", "Martin SjÃ¶lund <martin.sjolund@liu.se>", "John Tinnerholm <john.tinnerholm@liu.se>"]
version = "0.0.0"

[deps]
Absyn = "ce2f92e2-a952-11e9-0543-8b443f216f1d"
ExportAll = "ad2082ca-a69e-11e9-38fa-e96309a31fe4"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ImmutableList = "4a558cac-c1ed-11e9-20da-3584bcd8709a"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MetaModelica = "9d7f2a79-07b5-5542-8b19-c0100dda6b06"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
julia = "1.1"
